name: MyGitHubAction

on:
  push:

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repository
      uses: actions/checkout@v1
      
    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        architecture: 'x64'
    
    - name: Install pytest
      run: pip install pytest
      
    - name: View repository files
      run: ls -a
      
#     - name: Python Style Checker
#       uses: andymckay/pycodestyle-action@0.1.3
      
    - name: Run tests
      run: |
          cd test
          pytest -v -s test.py
  
  CI/CD:
    runs-on: ubuntu-latest
    needs: my_testing
    
    steps:
    
    - name: Git clone my repository
      uses: actions/checkout@v1
      
    - name: View repository files
      run: ls -a
    
    - name: Work With Docker
      run:  echo "aloxomora" | docker login -u "thisisdasha" --password-stdin
    - name: Build image
      run: docker build -t thisisdasha/mybotapp:latest -f Dockerfile .
    - name: Push image to docker
      run: docker push thisisdasha/mybotapp:latest


       